#!/usr/bin/env python3
"""
Generates the versionimports package that blank-imports all version packages
so their init() functions run and register with the version registry.
"""

import json
import os
import sys


def main():
    specs_dir = "openapi-specs"
    output_dir = "internal/provider/versionimports"
    module = "github.com/blastwaveinc/terraform-provider-blastshield"

    if not os.path.isdir(specs_dir):
        print(f"Error: {specs_dir} directory not found", file=sys.stderr)
        sys.exit(1)

    # Collect version package names from spec files
    pkg_names = []
    for filename in sorted(os.listdir(specs_dir)):
        if not filename.endswith(".json"):
            continue
        spec_path = os.path.join(specs_dir, filename)
        with open(spec_path) as f:
            spec = json.load(f)
        version = spec.get("info", {}).get("version", "")
        if not version:
            continue
        pkg_name = "v" + version.replace(".", "_")
        pkg_names.append(pkg_name)

    if not pkg_names:
        print("Warning: no spec files found in openapi-specs/", file=sys.stderr)

    os.makedirs(output_dir, exist_ok=True)

    # Generate imports.go
    output_path = os.path.join(output_dir, "imports.go")
    lines = [
        "// Code generated by generate_imports.py. DO NOT EDIT.",
        "",
        "package versionimports",
        "",
        "import (",
    ]
    for pkg in pkg_names:
        lines.append(f'\t_ "{module}/internal/provider/{pkg}"')
    lines.append(")")
    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {output_path} with {len(pkg_names)} version imports")


if __name__ == "__main__":
    main()
